In [1]:
import numpy as np 
import pandas as pd

In [2]:
dataset=pd.read_csv("bank.csv")

In [3]:
dataset

age          job  marital  education default  balance housing loan  \
0       59       admin.  married  secondary      no     2343     yes   no   
1       56       admin.  married  secondary      no       45      no   no   
2       41   technician  married  secondary      no     1270     yes   no   
3       55     services  married  secondary      no     2476     yes   no   
4       54       admin.  married   tertiary      no      184      no   no   
...    ...          ...      ...        ...     ...      ...     ...  ...   
11157   33  blue-collar   single    primary      no        1     yes   no   
11158   39     services  married  secondary      no      733      no   no   
11159   32   technician   single  secondary      no       29      no   no   
11160   43   technician  married  secondary      no        0      no  yes   
11161   34   technician  married  secondary      no        0      no   no   

        contact  day month  duration  campaign  pdays  previous poutcome  \
0       unknown    5   may      1042         1     -1         0  unknown   
1       unknown    5   may      1467         1     -1         0  unknown   
2       unknown    5   may      1389         1     -1         0  unknown   
3       unknown    5   may       579         1     -1         0  unknown   
4       unknown    5   may       673         2     -1         0  unknown   
...         ...  ...   ...       ...       ...    ...       ...      ...   
11157  cellular   20   apr       257         1     -1         0  unknown   
11158   unknown   16   jun        83         4     -1         0  unknown   
11159  cellular   19   aug       156         2     -1         0  unknown   
11160  cellular    8   may         9         2    172         5  failure   
11161  cellular    9   jul       628         1     -1         0  unknown   

      deposit  
0         yes  
1         yes  
2         yes  
3         yes  
4         yes  
...       ...  
11157      no  
11158      no  
11159      no  
11160      no  
11161      no  

[11162 rows x 17 columns]

In [4]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11162 entries, 0 to 11161
Data columns (total 17 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   age        11162 non-null  int64 
 1   job        11162 non-null  object
 2   marital    11162 non-null  object
 3   education  11162 non-null  object
 4   default    11162 non-null  object
 5   balance    11162 non-null  int64 
 6   housing    11162 non-null  object
 7   loan       11162 non-null  object
 8   contact    11162 non-null  object
 9   day        11162 non-null  int64 
 10  month      11162 non-null  object
 11  duration   11162 non-null  int64 
 12  campaign   11162 non-null  int64 
 13  pdays      11162 non-null  int64 
 14  previous   11162 non-null  int64 
 15  poutcome   11162 non-null  object
 16  deposit    11162 non-null  object
dtypes: int64(7), object(10)
memory usage: 1.4+ MB


In [5]:
dataset.isnull().any()

age          False
job          False
marital      False
education    False
default      False
balance      False
housing      False
loan         False
contact      False
day          False
month        False
duration     False
campaign     False
pdays        False
previous     False
poutcome     False
deposit      False
dtype: bool

In [6]:
x= dataset.iloc[:,0:16].values

In [7]:
x

array([[59, 'admin.', 'married', ..., -1, 0, 'unknown'],
       [56, 'admin.', 'married', ..., -1, 0, 'unknown'],
       [41, 'technician', 'married', ..., -1, 0, 'unknown'],
       ...,
       [32, 'technician', 'single', ..., -1, 0, 'unknown'],
       [43, 'technician', 'married', ..., 172, 5, 'failure'],
       [34, 'technician', 'married', ..., -1, 0, 'unknown']], dtype=object)

In [8]:
y= dataset.iloc[:,16:17].values

In [9]:
y

array([['yes'],
       ['yes'],
       ['yes'],
       ...,
       ['no'],
       ['no'],
       ['no']], dtype=object)

In [10]:
x.shape

(11162, 16)

In [11]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [12]:
dataset['job'].unique()

array(['admin.', 'technician', 'services', 'management', 'retired',
       'blue-collar', 'unemployed', 'entrepreneur', 'housemaid',
       'unknown', 'self-employed', 'student'], dtype=object)

In [16]:
print(dataset["marital"].unique())
print(dataset["education"].unique())
print(dataset["default"].unique())
print(dataset["housing"].unique())
print(dataset["loan"].unique())
print(dataset["contact"].unique())
print(dataset["month"].unique())
print(dataset["poutcome"].unique())
print(dataset["deposit"].unique())

['married' 'single' 'divorced']
['secondary' 'tertiary' 'primary' 'unknown']
['no' 'yes']
['yes' 'no']
['no' 'yes']
['unknown' 'cellular' 'telephone']
['may' 'jun' 'jul' 'aug' 'oct' 'nov' 'dec' 'jan' 'feb' 'mar' 'apr' 'sep']
['unknown' 'other' 'failure' 'success']
['yes' 'no']


In [17]:
ct=ColumnTransformer([("one",OneHotEncoder(),[1,2,3,4,6,7,8,10,15])],remainder="passthrough")
x=ct.fit_transform(x)

In [18]:
x

array([[1.0, 0.0, 0.0, ..., 1, -1, 0],
       [1.0, 0.0, 0.0, ..., 1, -1, 0],
       [0.0, 0.0, 0.0, ..., 1, -1, 0],
       ...,
       [0.0, 0.0, 0.0, ..., 2, -1, 0],
       [0.0, 0.0, 0.0, ..., 2, 172, 5],
       [0.0, 0.0, 0.0, ..., 1, -1, 0]], dtype=object)

In [19]:
x.shape

(11162, 51)

In [20]:
ct1 = ColumnTransformer([('one', OneHotEncoder(), [0])], remainder = 'passthrough')
y= ct1.fit_transform(y)

In [21]:
y

array([[0., 1.],
       [0., 1.],
       [0., 1.],
       ...,
       [1., 0.],
       [1., 0.],
       [1., 0.]])

In [22]:
y.shape

(11162, 2)

In [23]:
from sklearn.model_selection import train_test_split

In [24]:
x_train,x_test,y_train,y_test = train_test_split(x,y, test_size = 0.2,random_state = 0)

In [25]:
x_train

array([[0.0, 0.0, 0.0, ..., 1, -1, 0],
       [0.0, 0.0, 0.0, ..., 1, -1, 0],
       [0.0, 1.0, 0.0, ..., 5, -1, 0],
       ...,
       [0.0, 0.0, 0.0, ..., 8, -1, 0],
       [1.0, 0.0, 0.0, ..., 1, -1, 0],
       [0.0, 0.0, 0.0, ..., 1, -1, 0]], dtype=object)

In [26]:
y_train

array([[1., 0.],
       [0., 1.],
       [0., 1.],
       ...,
       [1., 0.],
       [1., 0.],
       [0., 1.]])

In [27]:
print("x_train shape", "\t", x_train.shape)
print("x_test shape", "\t", x_test.shape)
print("y_train shape", "\t", y_train.shape)
print("y_test shape", "\t", y_test.shape)
print("x shape", "\t", x.shape)
print("y shape", "\t", y.shape)


x_train shape 	 (8929, 51)
x_test shape 	 (2233, 51)
y_train shape 	 (8929, 2)
y_test shape 	 (2233, 2)
x shape 	 (11162, 51)
y shape 	 (11162, 2)


In [28]:
from sklearn.preprocessing import StandardScaler

In [29]:
sc=StandardScaler()

In [30]:
x_train=sc.fit_transform(x_train)
x_test =sc.fit_transform(x_test)

In [31]:
x_train

array([[-0.37172192, -0.45760242, -0.17658264, ..., -0.56394809,
        -0.48428507, -0.35888264],
       [-0.37172192, -0.45760242, -0.17658264, ..., -0.56394809,
        -0.48428507, -0.35888264],
       [-0.37172192,  2.18530314, -0.17658264, ...,  0.92827075,
        -0.48428507, -0.35888264],
       ...,
       [-0.37172192, -0.45760242, -0.17658264, ...,  2.04743488,
        -0.48428507, -0.35888264],
       [ 2.69018306, -0.45760242, -0.17658264, ..., -0.56394809,
        -0.48428507, -0.35888264],
       [-0.37172192, -0.45760242, -0.17658264, ..., -0.56394809,
        -0.48428507, -0.35888264]])

In [32]:
x_test

array([[-0.35506564, -0.46571851, -0.16329932, ..., -0.51893725,
         2.62409874,  0.62465525],
       [-0.35506564, -0.46571851, -0.16329932, ..., -0.51893725,
         1.30248101,  1.63872661],
       [-0.35506564, -0.46571851, -0.16329932, ..., -0.17189116,
        -0.46885387, -0.38941612],
       ...,
       [-0.35506564, -0.46571851, -0.16329932, ..., -0.17189116,
        -0.46885387, -0.38941612],
       [ 2.81638066, -0.46571851, -0.16329932, ..., -0.51893725,
        -0.46885387, -0.38941612],
       [-0.35506564, -0.46571851, -0.16329932, ..., -0.17189116,
        -0.46885387, -0.38941612]])

In [33]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [34]:
bank = Sequential()

In [35]:
bank.add(Dense(units=51,kernel_initializer='random_uniform',activation='relu'))

In [36]:
bank.add(Dense(units=102,kernel_initializer='random_uniform',activation='relu'))

In [37]:
bank.add(Dense(units=102,kernel_initializer='random_uniform',activation='relu'))

In [38]:
bank.add(Dense(units=2,kernel_initializer='random_uniform',activation='softmax'))

In [39]:
bank.compile(optimizer = "rmsprop", loss = "categorical_crossentropy", metrics=["accuracy"])

In [40]:
bank.fit(x_train, y_train, epochs = 25)

Epoch 1/25
280/280 [==============================] - 1s 898us/step - loss: 0.4225 - accuracy: 0.8132
Epoch 2/25
280/280 [==============================] - 0s 958us/step - loss: 0.3618 - accuracy: 0.8474
Epoch 3/25
280/280 [==============================] - 0s 994us/step - loss: 0.3504 - accuracy: 0.8542
Epoch 4/25
280/280 [==============================] - 0s 989us/step - loss: 0.3389 - accuracy: 0.8605
Epoch 5/25
280/280 [==============================] - 0s 1ms/step - loss: 0.3315 - accuracy: 0.8635
Epoch 6/25
280/280 [==============================] - 0s 878us/step - loss: 0.3255 - accuracy: 0.8665
Epoch 7/25
280/280 [==============================] - 0s 934us/step - loss: 0.3186 - accuracy: 0.8709
Epoch 8/25
280/280 [==============================] - 0s 930us/step - loss: 0.3141 - accuracy: 0.8734
Epoch 9/25
280/280 [==============================] - 0s 991us/step - loss: 0.3090 - accuracy: 0.8746
Epoch 10/25
280/280 [==============================] - 0s 946us/step - loss: 0.3047 

In [41]:
ypred=bank.predict(x_test)

In [42]:
ypred

array([[9.9936324e-01, 6.3671859e-04],
       [5.3209201e-03, 9.9467909e-01],
       [9.9956161e-01, 4.3839484e-04],
       ...,
       [1.4285862e-01, 8.5714138e-01],
       [7.1352935e-01, 2.8647068e-01],
       [9.8494118e-01, 1.5058816e-02]], dtype=float32)

In [43]:
y_test

array([[1., 0.],
       [0., 1.],
       [1., 0.],
       ...,
       [0., 1.],
       [0., 1.],
       [1., 0.]])

In [44]:
ypred=ypred>0.5

In [45]:
ypred

array([[ True, False],
       [False,  True],
       [ True, False],
       ...,
       [False,  True],
       [ True, False],
       [ True, False]])

In [46]:
y_test

array([[1., 0.],
       [0., 1.],
       [1., 0.],
       ...,
       [0., 1.],
       [0., 1.],
       [1., 0.]])

In [47]:
dataset.head(1)

age     job  marital  education default  balance housing loan  contact  \
0   59  admin.  married  secondary      no     2343     yes   no  unknown   

   day month  duration  campaign  pdays  previous poutcome deposit  
0    5   may      1042         1     -1         0  unknown     yes

In [48]:
yp = bank.predict(sc.transform(ct.transform([[40, "management", "married", "secondary", "no", 4025, "yes", "no", "cellular", 15, "jul", 107, 4, -1, 0, "unknown"]])))

In [52]:
yp=yp>0.5


In [54]:
dataset["deposit"].unique()

array(['yes', 'no'], dtype=object)

In [53]:
yp#yes 

array([[ True, False]])