In [1]:
#data preprocessing 
import numpy as np 
import pandas as pd 

In [2]:
dataset= pd.read_csv("50_Startups.csv")

In [3]:
dataset 

R&D Spend  Administration  Marketing Spend       State     Profit
0   165349.20       136897.80        471784.10    New York  192261.83
1   162597.70       151377.59        443898.53  California  191792.06
2   153441.51       101145.55        407934.54     Florida  191050.39
3   144372.41       118671.85        383199.62    New York  182901.99
4   142107.34        91391.77        366168.42     Florida  166187.94
5   131876.90        99814.71        362861.36    New York  156991.12
6   134615.46       147198.87              NaN  California  156122.51
7   130298.13       145530.06        323876.68     Florida  155752.60
8   120542.52       148718.95        311613.29    New York  152211.77
9   123334.88       108679.17        304981.62  California  149759.96
10  101913.08             NaN        229160.95     Florida  146121.95
11  100671.96        91790.61        249744.55  California  144259.40
12   93863.75       127320.38        249839.44     Florida  141585.52
13   91992.39       135495.07        252664.93  California  134307.35
14  119943.24       156547.42        256512.92     Florida  132602.65
15  114523.61       122616.84        261776.23    New York  129917.04
16   78013.11       121597.55        264346.06  California  126992.93
17   94657.16       145077.58        282574.31    New York  125370.37
18   91749.16       114175.79        294919.57     Florida  124266.90
19   86419.70       153514.11             0.00    New York  122776.86
20   76253.86       113867.30        298664.47  California  118474.03
21   78389.47       153773.43        299737.29    New York  111313.02
22   73994.56       122782.75        303319.26     Florida  110352.25
23   67532.53       105751.03        304768.73     Florida  108733.99
24   77044.01        99281.34        140574.81    New York  108552.04
25   64664.71       139553.16        137962.62  California  107404.34
26   75328.87       144135.98        134050.07     Florida  105733.54
27   72107.60       127864.55        353183.81    New York  105008.31
28   66051.52       182645.56        118148.20     Florida  103282.38
29   65605.48       153032.06        107138.38    New York  101004.64
30   61994.48       115641.28         91131.24     Florida   99937.59
31   61136.38       152701.92         88218.23    New York   97483.56
32   63408.86       129219.61         46085.25  California   97427.84
33   55493.95       103057.49        214634.81     Florida   96778.92
34   46426.07       157693.92        210797.67  California   96712.80
35   46014.02        85047.44        205517.64    New York   96479.51
36   28663.76       127056.21        201126.82     Florida   90708.19
37   44069.95        51283.14        197029.42  California   89949.14
38   20229.59        65947.93        185265.10    New York   81229.06
39   38558.51        82982.09        174999.30  California   81005.76
40   28754.33       118546.05        172795.67  California   78239.91
41   27892.92        84710.77        164470.71     Florida   77798.83
42   23640.93        96189.63        148001.11  California   71498.49
43   15505.73       127382.30         35534.17    New York   69758.98
44   22177.74       154806.14         28334.72  California   65200.33
45    1000.23       124153.04          1903.93    New York   64926.08
46    1315.46       115816.21        297114.46     Florida   49490.75
47       0.00       135426.92             0.00  California   42559.73
48     542.05        51743.15             0.00    New York   35673.41
49       0.00       116983.80         45173.06  California   14681.40

In [4]:
dataset.head()

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [5]:
dataset.describe()

R&D Spend  Administration  Marketing Spend         Profit
count      50.000000       49.000000        49.000000      50.000000
mean    73721.615600   121564.038163    212725.266735  112012.639200
std     45902.256482    28264.721000    122959.103760   40306.180338
min         0.000000    51283.140000         0.000000   14681.400000
25%     39936.370000   103057.490000    134050.070000   90138.902500
50%     73051.080000   122782.750000    214634.810000  107978.190000
75%    101602.800000   145077.580000    299737.290000  139765.977500
max    165349.200000   182645.560000    471784.100000  192261.830000

In [6]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   R&D Spend        50 non-null     float64
 1   Administration   49 non-null     float64
 2   Marketing Spend  49 non-null     float64
 3   State            50 non-null     object 
 4   Profit           50 non-null     float64
dtypes: float64(4), object(1)
memory usage: 2.1+ KB


In [7]:
#checking for null values 
dataset.isnull().any()

R&D Spend          False
Administration      True
Marketing Spend     True
State              False
Profit             False
dtype: bool

In [8]:
dataset.isnull().sum()

R&D Spend          0
Administration     1
Marketing Spend    1
State              0
Profit             0
dtype: int64

In [9]:
dataset['Administration'].mean()

121564.03816326526

In [10]:
dataset['Marketing Spend'].mean()

212725.26673469393

In [11]:
dataset['Administration'].fillna(dataset['Administration'].mean(),inplace=True)
dataset['Marketing Spend'].fillna(dataset['Marketing Spend'].mean(),inplace=True)


In [12]:
dataset.isnull().any()

R&D Spend          False
Administration     False
Marketing Spend    False
State              False
Profit             False
dtype: bool

In [13]:
x=dataset.iloc[:,0:4].values
y=dataset.iloc[:,4:5].values
x

array([[165349.2, 136897.8, 471784.1, 'New York'],
       [162597.7, 151377.59, 443898.53, 'California'],
       [153441.51, 101145.55, 407934.54, 'Florida'],
       [144372.41, 118671.85, 383199.62, 'New York'],
       [142107.34, 91391.77, 366168.42, 'Florida'],
       [131876.9, 99814.71, 362861.36, 'New York'],
       [134615.46, 147198.87, 212725.26673469393, 'California'],
       [130298.13, 145530.06, 323876.68, 'Florida'],
       [120542.52, 148718.95, 311613.29, 'New York'],
       [123334.88, 108679.17, 304981.62, 'California'],
       [101913.08, 121564.03816326526, 229160.95, 'Florida'],
       [100671.96, 91790.61, 249744.55, 'California'],
       [93863.75, 127320.38, 249839.44, 'Florida'],
       [91992.39, 135495.07, 252664.93, 'California'],
       [119943.24, 156547.42, 256512.92, 'Florida'],
       [114523.61, 122616.84, 261776.23, 'New York'],
       [78013.11, 121597.55, 264346.06, 'California'],
       [94657.16, 145077.58, 282574.31, 'New York'],
       [91749.16

In [14]:
y

array([[192261.83],
       [191792.06],
       [191050.39],
       [182901.99],
       [166187.94],
       [156991.12],
       [156122.51],
       [155752.6 ],
       [152211.77],
       [149759.96],
       [146121.95],
       [144259.4 ],
       [141585.52],
       [134307.35],
       [132602.65],
       [129917.04],
       [126992.93],
       [125370.37],
       [124266.9 ],
       [122776.86],
       [118474.03],
       [111313.02],
       [110352.25],
       [108733.99],
       [108552.04],
       [107404.34],
       [105733.54],
       [105008.31],
       [103282.38],
       [101004.64],
       [ 99937.59],
       [ 97483.56],
       [ 97427.84],
       [ 96778.92],
       [ 96712.8 ],
       [ 96479.51],
       [ 90708.19],
       [ 89949.14],
       [ 81229.06],
       [ 81005.76],
       [ 78239.91],
       [ 77798.83],
       [ 71498.49],
       [ 69758.98],
       [ 65200.33],
       [ 64926.08],
       [ 49490.75],
       [ 42559.73],
       [ 35673.41],
       [ 14681.4 ]])

In [15]:
dataset['State'].unique()

array(['New York', 'California', 'Florida'], dtype=object)

In [16]:
x.shape
print(x)

[[165349.2 136897.8 471784.1 'New York']
 [162597.7 151377.59 443898.53 'California']
 [153441.51 101145.55 407934.54 'Florida']
 [144372.41 118671.85 383199.62 'New York']
 [142107.34 91391.77 366168.42 'Florida']
 [131876.9 99814.71 362861.36 'New York']
 [134615.46 147198.87 212725.26673469393 'California']
 [130298.13 145530.06 323876.68 'Florida']
 [120542.52 148718.95 311613.29 'New York']
 [123334.88 108679.17 304981.62 'California']
 [101913.08 121564.03816326526 229160.95 'Florida']
 [100671.96 91790.61 249744.55 'California']
 [93863.75 127320.38 249839.44 'Florida']
 [91992.39 135495.07 252664.93 'California']
 [119943.24 156547.42 256512.92 'Florida']
 [114523.61 122616.84 261776.23 'New York']
 [78013.11 121597.55 264346.06 'California']
 [94657.16 145077.58 282574.31 'New York']
 [91749.16 114175.79 294919.57 'Florida']
 [86419.7 153514.11 0.0 'New York']
 [76253.86 113867.3 298664.47 'California']
 [78389.47 153773.43 299737.29 'New York']
 [73994.56 122782.75 303319.26 

In [17]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [18]:
ct = ColumnTransformer([('one',OneHotEncoder(),[3])],remainder='passthrough')


In [19]:
x=ct.fit_transform(x)


In [20]:
x.shape

(50, 6)

In [21]:
x[0]

array([0.0, 0.0, 1.0, 165349.2, 136897.8, 471784.1], dtype=object)

In [22]:
#split data into x and y 
from sklearn.model_selection import train_test_split 
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2,random_state = 0)

In [23]:
print(x.shape,"xshape")
print(y.shape,"yshape")
print(x_train.shape,"x_train shape")
print(x_test.shape,"x_test shape")
print(y_train.shape,"y_train shape")
print(y_test.shape,"y_test shape")

(50, 6) xshape
(50, 1) yshape
(40, 6) x_train shape
(10, 6) x_test shape
(40, 1) y_train shape
(10, 1) y_test shape


In [24]:
from sklearn.preprocessing import StandardScaler
d=StandardScaler()
x_train=d.fit_transform(x_train)
x_test=d.fit_transform(x_test)

In [25]:
x_train

array([[-0.81649658,  1.73205081, -0.73379939, -0.35006454, -0.78547109,
         0.08437197],
       [-0.81649658, -0.57735027,  1.36277029, -0.55530319, -1.48117426,
         0.010183  ],
       [-0.81649658,  1.73205081, -0.73379939,  0.07935762,  0.80133381,
        -0.57136866],
       [ 1.22474487, -0.57735027, -0.73379939, -0.54638238,  1.32505817,
         0.05314808],
       [-0.81649658,  1.73205081, -0.73379939,  0.43485371, -0.35598663,
         0.73767158],
       [-0.81649658,  1.73205081, -0.73379939,  1.26943143,  0.85518519,
         0.9733037 ],
       [-0.81649658,  1.73205081, -0.73379939,  1.04525007,  1.28077047,
         0.42514589],
       [-0.81649658, -0.57735027,  1.36277029, -1.529843  ,  0.02942065,
        -1.64667886],
       [-0.81649658, -0.57735027,  1.36277029, -1.53976251, -2.76767264,
        -1.66217167],
       [-0.81649658, -0.57735027,  1.36277029, -0.13115188,  1.14497701,
        -0.79035663],
       [-0.81649658, -0.57735027,  1.36277029,  0.

In [26]:
x_test

array([[-0.33333333,  0.81649658, -0.65465367, -0.38506601,  2.07412535,
        -1.23963153],
       [ 3.        , -1.22474487, -0.65465367,  0.45320659, -0.68127394,
         0.03072863],
       [-0.33333333,  0.81649658, -0.65465367,  0.48325811,  0.22167832,
        -0.16797433],
       [-0.33333333,  0.81649658, -0.65465367, -1.30900888, -0.89598746,
        -0.79245901],
       [-0.33333333,  0.81649658, -0.65465367,  1.73092772, -0.39756243,
         1.55780945],
       [-0.33333333, -1.22474487,  1.52752523, -0.23842877,  0.4127568 ,
         1.02927544],
       [-0.33333333, -1.22474487,  1.52752523, -1.49456284, -1.46501663,
        -0.59172119],
       [-0.33333333, -1.22474487,  1.52752523, -0.50407742,  1.16601099,
        -1.52855931],
       [-0.33333333,  0.81649658, -0.65465367, -0.19273938,  0.25863875,
         0.54790998],
       [-0.33333333,  0.81649658, -0.65465367,  1.45649088, -0.69336975,
         1.15462186]])

In [54]:
#model building 
from tensorflow.keras.models import Sequential 
from tensorflow.keras.layers import Dense 

In [55]:
rg= Sequential()

In [56]:
x_train.shape

(40, 6)

In [57]:
rg.add(Dense(units= 6,kernel_initializer='random_uniform',activation='relu'))

In [58]:
rg.add(Dense(units=12,kernel_initializer='random_uniform',activation='relu'))

In [59]:
rg.add(Dense(units= 1,kernel_initializer='random_uniform',activation='relu'))

In [60]:
rg.compile(optimizer='adam',loss='mse', metrics=['mse'])

In [81]:
rg.fit(x_train,y_train,epochs=10000)#model evaluation

Epoch 1/10000
2/2 [==============================] - 0s 1ms/step - loss: 12861619200.0000 - mse: 12861619200.0000
Epoch 2/10000
2/2 [==============================] - 0s 3ms/step - loss: 12859624448.0000 - mse: 12859624448.0000
Epoch 3/10000
2/2 [==============================] - 0s 4ms/step - loss: 12857720832.0000 - mse: 12857720832.0000
Epoch 4/10000
2/2 [==============================] - 0s 2ms/step - loss: 12855718912.0000 - mse: 12855718912.0000
Epoch 5/10000
2/2 [==============================] - 0s 4ms/step - loss: 12853872640.0000 - mse: 12853872640.0000
Epoch 6/10000
2/2 [==============================] - 0s 3ms/step - loss: 12851899392.0000 - mse: 12851899392.0000
Epoch 7/10000
2/2 [==============================] - 0s 2ms/step - loss: 12849956864.0000 - mse: 12849956864.0000
Epoch 8/10000
2/2 [==============================] - 0s 4ms/step - loss: 12848189440.0000 - mse: 12848189440.0000
Epoch 9/10000
2/2 [==============================] - 0s 3ms/step - loss: 12846240768.000

In [82]:
ypred = rg.predict(x_test)

In [83]:
y_test

array([[103282.38],
       [144259.4 ],
       [146121.95],
       [ 77798.83],
       [191050.39],
       [105008.31],
       [ 81229.06],
       [ 97483.56],
       [110352.25],
       [166187.94]])

In [84]:
ypred

array([[ 81016.62 ],
       [183309.58 ],
       [ 92737.   ],
       [ 40859.086],
       [159284.05 ],
       [118533.41 ],
       [ 77082.51 ],
       [105783.82 ],
       [ 72801.48 ],
       [140528.53 ]], dtype=float32)

In [85]:
ypred[0]

array([81016.62], dtype=float32)

In [86]:
np.argmax(ypred[0])

0

In [87]:
ypred = ypred > 0.5

In [88]:
ypred

array([[ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True]])

In [89]:
dataset.head(6)

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94
5  131876.90        99814.71        362861.36    New York  156991.12

In [90]:
yp = rg.predict(d.transform(ct.transform([[162597.70, 151377.59,443898.53 , 'California']])))#1st row

In [91]:
yp

array([[247252.52]], dtype=float32)